radan_travel/config/routes.rb
Rails.application.routes.draw do
  

  resources :iran_tour_reservs

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", :locale => /en|fa|ar/ do  
    resources :category_countries
    resources :continent_categories
    resources :visas
    resources :pdf_investments

    resources :investment_in_irans

    resources :passengers

    resources :visa_forms
    resources :visa_types

    resources :class_hotels
    resources :slides
    resources :locationtours do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end
    resources :custom_tours
    resources :planes
    resources :hotels do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end

    resources :cities do
      collection do
        get :dynamic_city
        get :show_fun_tours_for_city
      end
    end
    resources :countries do
      collection do
        get :show_fun_tours_for_country
      end
    end

    resources :tours do
      collection do
        post :search 
        get :tours_moment
        
      end
      member do
        get :sendtonewsletter
        get :iran_tour
      end
    end

    resources :photos

    resources :sights

    resources :links

    resources :roles

    devise_for :users
      
    resources :users

    resources :pages
    resources :send_links

    resources :customers do
      collection do
        post :search
        post :send_email_to_all
      end
    end

    resources :messages

    resources :tour_comments do
        member do
          get :confirm
        end
      end

  end
  
  root :to => 'static#index'
  get "index" => 'static#index'

  get "home" => 'static#home'

  get "google46bde3a8d7d48d7d" => 'static#google46bde3a8d7d48d7d'
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  get "BingSiteAuth.xml" => "static#BingSiteAuth", :format => "xml", :as => :BingSiteAuth
  
  get '/html_with_images', :to => 'tours#html_with_images'
  get '/html_with_table', :to => 'tours#html_with_table'
  get '/to_pdf_images', :to => 'tours#to_pdf_images'
  get '/to_pdf_table', :to => 'tours#to_pdf_table'
  get '/to_pdf_tour_show', :to => 'tours#to_pdf_tour_show'

  
end

radan_travel/app/models/country.rb
# encoding: UTF-8
class Country < ActiveRecord::Base
  has_attached_file :country_flag, :styles => { :original => "200x250>" , :small => "30x35#" }
  validates_attachment :country_flag, 
    :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png"], :message => "فرمت عکس پرچم صحیح نمی باشد." },
    :size => { :in => 0..20.kilobytes , :message => "حجم تصویر پرچم بیشتر از ۲۰ کیلوبایت است."}
  validates :title_en, :title_fa, :title_ar, :continent_category_id,  :presence => {:message => 'فیلدهای ضروری را پر کنید'}
  validates :title_fa, :title_en, :title_ar, :uniqueness => {:message => 'عنوان تکراری است'}
    
  extend FriendlyId  
  friendly_id :title_en
  has_many :cities, dependent: :destroy
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
  belongs_to :continent_category
  belongs_to :category_country
  has_many :tours
  def title
    if I18n.locale == :ar
      self.read_attribute("title_ar")
    elsif I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def text
    if I18n.locale == :ar
      self.read_attribute("text_ar")
    elsif I18n.locale == :en
      self.read_attribute("text_en")
    else
      self.read_attribute("text_fa")
    end    
  end
end

radan_travel/app/controllers/countries_controller.rb
# encoding: UTF-8
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.order(" created_at desc")
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end
  def show_fun_tours_for_country
    
    @country = Country.find(params[:country_id])    
    @tour_group = ContinentCategory.find(params[:continent_id])
    
    
  end

  # GET /countries/new
  def new
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(:title_fa, :title_en, :title_ar, :text_fa, :text_en, :text_ar, 
      :country_flag, :continent_category_id, :show_in_submenu, :category_country_id,
      photos_attributes: [:id, :image, :description_fa, :description_en, :description_ar, :country_id, :_destroy, :_update] 
      )
    end
end

radan_travel/app/helpers/countries_helper.rb
module CountriesHelper
end

radan_travel/app/views/countries/_country_details.html.haml
-@countries.each do  |country|
  .tab-pane.fade.in.country-details{:role => "tabpanel", :id => 'country'+country.id.to_s}    
    - if is_admin?      
      = link_to 'ویرایش', edit_country_path(country), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
    
    .country-show{:class => I18n.locale}
      -#
        .col-xs-5.set-center.margin-bottom{:style => "overflow:hidden"}
          - if country.photos.present?
            = link_to  country.photos.first.image(:original), "data-lightbox" => "example-set",  :title => 'آژانس هواپیمایی رادان سیر_' + country.title do
              = image_tag country.photos.first.image(:medium), :class => "example-image", :title => 'آژانس هواپیمایی رادان سیر_' + country.title, :alt => 'آژانس هواپیمایی رادان سیر_' + country.title,  :id => "country-photos-" + country.photos.first.id.to_s

      .col-xs-12.country-text.margin-bottom{:class => I18n.locale}        
        %p
          %h2.country-title{:class => I18n.locale}            
            - if country.category_country_id.present?
              %span{:class => I18n.locale}=  country.category_country.title + ','
            = country.title
            
        .margin-bottom5{:class => I18n.locale}
          = raw country.text  
      .col-xs-12.margin-bottom5#cities-list
        .title-line.col-xs-10
        %p.col-xs-2.set-center.title{:class => I18n.locale}= t('city')      
        .country-cities-list.margin-bottom5          
          %ul{:style => "list-style:disc; margin-top:5%;", :title => "آژانس_هواپیمایی_رادان_سیر"}
            - country.cities.each do |city| 
              - if I18n.locale == :en
                %li.col-xs-2.pull-left{:class => I18n.locale}= link_to  city.title, city, :title => "آژانس_هواپیمایی_رادان_سیر"+ "_" + city.title_fa, :id => "city-"+city.id.to_s, :class => I18n.locale
              - else
                %li.col-xs-2.pull-right{:class => I18n.locale}= link_to  city.title, city, :title => "آژانس_هواپیمایی_رادان_سیر"+ "_" + city.title_fa, :id => "city-"+city.id.to_s, :class => I18n.locale
    
      .col-xs-12.margin-bottom5#cities-sights
        .title-line.col-xs-10
        %p.col-xs-2.set-center.title{:class => I18n.locale}= t('sights')            
        .col-xs-12.margin-bottom5  
          - if country.cities.present?
            - country.cities.each do |city|
              - if city.sights.present?
                - city.sights.each do |sight|
                  .col-xs-12.country-sights.margin-top5{:class =>  cycle("odd", "even")}
                    - if is_admin?
                      = link_to 'ویرایش ', edit_sight_path(sight), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
                      = link_to 'حذف ', sight, :method => :delete, :data => { :confirm => 'آیا می خواهید این تور را حذف کنید؟' }, :class => "btn btn-danger", :title => "آژانس_هواپیمایی_رادان_سیر"
                    .col-xs-7.sights-info
                      %h2{:class => I18n.locale}= sight.title
                      .col-xs-12.margin-top5#sight-text= raw sight.text
                    .col-xs-5#city-sights-slider
                      - if sight.photos.present? 
                        - if sight.photos.count <= 1
                          = image_tag sight.photos.first.image(:medium)
                        - else
                          = render 'shared/slight_slider', :pictures => sight.photos, :sight => sight
                      
                    
        
          
            

radan_travel/app/views/countries/_country_title_tap.html.haml
- Country.all.each do  |country|
  %li{:role => "presentation",  :title => "آژانس_هواپیمایی_رادان_سیر",:class => I18n.locale}
    = link_to  '#country'+country.id.to_s, :role => "tab", "data-toggle" => "tab", :title => "آژانس_هواپیمایی_رادان_سیر"+ "_" +country.title_fa, :id => 'country-'+ country.id.to_s, :class => "country-name" do
      %span.location= image_tag country.country_flag(:small)
      %span.country-title-tab= country.title

radan_travel/app/views/countries/_form.html.haml
= nested_form_for @country, :html => { :multipart => true, :class => "form-horizontal"  } do |f|

  - if @country.errors.any?
    #error_explanation      
      %ul
        - @country.errors.each do |attr, msg|
          %li= msg
  .row 
    -#
      .col-xs-12
        .form-group{:style => "background:#FFA500"}
          = f.label 'جهت نمایش در زیرمنو برای بخش هتلهای خارجی تیک زیر را برای این کشور فعال کنید.', :class => "control-label"
          = f.check_box :show_in_submenu, :class => "form-control"
    .col-xs-12
      .col-xs-6
        .form-group
          = f.label 'عنوان فارسی', :class => "control-label"
          = f.text_field :title_fa, :class => "form-control"
        .form-group
          = f.label 'عنوان انگلیسی', :class => "control-label"
          = f.text_field :title_en, :class => "form-control"
        .form-group
          = f.label 'عنوان عربی', :class => "control-label"
          = f.text_field :title_ar, :class => "form-control"
      .col-xs-6        
        .form-group
          = f.label 'گروبندی بر اساس قاره', :class => "control-label"
          = f.select :continent_category_id, options_for_select(ContinentCategory.all.collect{ |u| [u.title_fa, u.id] }, :selected => @country.continent_category_id), prompt: "قاره را انتخاب کنید.", :class => "form-control"  
        .form-group
          = f.label 'گروبندی بر اساس قاره', :class => "control-label"
          = f.select :category_country_id, options_for_select(CategoryCountry.all.collect{ |u| [u.title_fa, u.id] }, :selected => @country.category_country_id), prompt: "قاره را انتخاب کنید.", :class => "form-control"  
          
        .form-group
          - if @country.country_flag.present?
            = image_tag @country.country_flag(:original)
          = f.label 'پرچم کشور:', :class => "control-label"
          = f.file_field :country_flag, :class => "form-control"
      .col-xs-12
        .form-group.col-xs-12
          = f.label "برای افزودن تصاویر برای این پروژه دکمه زیر را فشار دهید و در کادری که نمایش داده می شود تصویر مورد نظر را انتخاب کنید:", :class => "control-label"
          = f.label "دقت داشته باشید حجم هر عکس باید کمتر از ۵۰۰کیلوبایت باشد.", :class => "control-label", :style=> "color:#ec523f"
          = f.link_to_add content_tag(:span, "افزودن تصویر", :class => "btn btn-warning"), :photos, :id => "add_new_picture", :class => "btn"
        
        .col-xs-12.form-group
          = f.fields_for :photos do |picture|  
            .col-xs-4
              = render "shared/upload_image_form", :picture => picture  
          
      

    .col-xs-12
      .form-group
        = f.label 'متن فارسی', :class => "control-label"
        .editor
          = f.text_area :text_fa, :class => "ckeditor form-control"
      .form-group
        = f.label 'متن انگلیسی', :class => "control-label"
        .editor  
          = f.text_area :text_en, :class => "ckeditor form-control"
      .form-group
        = f.label 'متن عربی', :class => "control-label"
        .editor
          = f.text_area :text_ar, :class => "ckeditor form-control"
      .form-group
        = f.submit 'ثبت', :class => "btn btn-primary"
        

radan_travel/app/views/countries/edit.html.haml
.margin3  
  %h1 ویرایش اطلاعات یک کشور

  = render 'form'
  - if is_admin?
    = link_to 'مشاهده', @country, :class => "btn btn-warning"      

radan_travel/app/views/countries/index.html.haml
.margin3
  -if is_admin?
    = link_to 'معرفی کشور', new_country_path, :class => "btn btn-success", :title => "آژانس_هواپیمایی_رادان_سیر"
  .col-xs-12.margin-bottom5
    .title-tour-line.col-xs-10
    %p.col-xs-3.set-center.title-tour{:class => I18n.locale}=  t('country')
  
  .country-tabs
    - if I18n.locale == :en  
      %ul.nav.nav-tabs.pull-left#CountryTab.col-xs-12{:role => "tablist", :class => I18n.locale }
        = render 'countries/country_title_tap'  
      .tab-content.col-xs-12.pull-left
        = render 'countries/country_details'
    - else
      %ul.nav.nav-tabs.pull-right#CountryTab.col-xs-12{:role => "tablist", :class => I18n.locale }
        = render 'countries/country_title_tap'    
      .tab-content.col-xs-12.pull-right
        = render 'countries/country_details'
      
  .keywords.full-width
    %p= t('Keywords.title')
    %ul.tag-cloud.full-width{:class => I18n.locale}
      %li.tag-cloud
        = link_to t('radantravel'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.a'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.b'), '/'              
      %li.tag-cloud
        = link_to t('Keywords.s'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.w'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.c'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.d'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.f'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.g'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.h'), Sight
      %li.tag-cloud
        = link_to t('Keywords.l'), Sight
      %li.tag-cloud
        = link_to t('Keywords.m'), Sight
      %li.tag-cloud
        = link_to t('Keywords.n'), Sight
      %li.tag-cloud
        = link_to t('Keywords.e'), '/' 
      %li.tag-cloud
        = link_to t('Keywords.p'), '/'   
:javascript
  $(function () {
    $('.tab-content .tab-pane:first').addClass('active');
    $('#CountryTab a:first').tab('show')
  });
  $('.country-title-tab').click(function(){    
    $('html, body').animate({ scrollTop: 800 }, 'fast'); 
  });

radan_travel/app/views/countries/new.html.haml
.margin3  
  %h1 کشور جدید

  = render 'form'

  = link_to 'بازگشت', countries_path

radan_travel/app/views/countries/show.html.haml
.margin3 
  - if is_admin?
    .col-xs-12
      = link_to 'ویرایش کشور', edit_country_path(@country), :class => "btn btn-info" 
  .col-xs-12.margin-bottom5
    .title-tour-line.col-xs-10
    %p.col-xs-3.set-center.title-tour{:class => I18n.locale}= @country.title
    
  .col-xs-12.margin-bottom5.country-text{:class => I18n.locale}= raw @country.text
  
  .col-xs-12.margin-bottom5
    .title-line.col-xs-10
    %p.col-xs-2.set-center.title{:class => I18n.locale}= t('city')
  .col-xs-12.margin-bottom5
    %ul{:class => I18n.locale}
      - @country.cities.order('title_fa asc').each do |city|
        - if I18n.locale == :en
          %li.col-xs-3.city-title.pull-left= link_to city.title, city
        - else
          %li.col-xs-3.city-title.pull-right= link_to city.title, city
  
  .col-xs-12.margin-bottom5  
    - @country.cities.order('title_fa asc').each do |city|
      -if city.hotels.present?
        .col-xs-12.margin-bottom5
          .title-line.col-xs-10
          %p.col-xs-2.set-center.title{:class => I18n.locale}= t('hotel') + ',' + city.title
        .show-tours.col-xs-12.set-center
          - city.hotels.order('title_fa asc').each_with_index do |hotel, i|
            .tours-index{:class => "iran-city-" + hotel.city.id.to_s, "data-my-order" => hotel.id}
              = link_to hotel, :class => "tour-box", :title => "آژانس_هواپیمایی_رادان_سیر" do
                %h5.tour-title{:id => "hotel-"+hotel.id.to_s, :class => I18n.locale}= hotel.title          
                - if hotel.photos.present?
                  .hover.panel{:id => "item-"+ (i+1).to_s}
                    .front
                      .pad.tour-sample-image= image_tag hotel.photos.first.image(:medium), :id => "tour-sample-image-" + hotel.photos.first.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
                    .back
                      .pad.tour-sample-image= image_tag hotel.photos.last.image(:medium), :id => "tour-sample-image-" + hotel.photos.last.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
                .clear-float 
                .some-info 
                  %p
                    %span=image_tag 'Star.png'
                    - if hotel.class_hotel_id.present?
                      %span.en= hotel.class_hotel.title
                  %p= hotel.city.country.title + ' , ' + hotel.city.title
              -if is_admin?
                .admin-btn-tour
                  = link_to 'مشاهده', hotel, :class => "btn btn-warning"   , :title => "آژانس_هواپیمایی_رادان_سیر"    
                  = link_to 'ویرایش', edit_hotel_path(hotel), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
                  = link_to 'حذف', hotel, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger", :title => "آژانس_هواپیمایی_رادان_سیر"
      

  
  
  
  .col-xs-12.margin-bottom5  
    - @country.cities.order('title_fa asc').each do |city|    
      - if city.sights.present?
        .col-xs-12.margin-bottom5
          .title-line.col-xs-10
          %p.col-xs-2.set-center.title{:class => I18n.locale}= t('sights') 
        .show-tours.col-xs-12.set-center
          - city.sights.order('title_fa asc').each_with_index do |hotel, i|
            .tours-index{:class => "iran-city-" + hotel.city.id.to_s, "data-my-order" => hotel.id}
              = link_to hotel, :class => "tour-box", :title => "آژانس_هواپیمایی_رادان_سیر" do
                %h5.tour-title{:id => "hotel-"+hotel.id.to_s, :class => I18n.locale}= hotel.title          
                - if hotel.photos.present?
                  .hover.panel{:id => "item-"+ (i+1).to_s}
                    .front
                      .pad.tour-sample-image= image_tag hotel.photos.first.image(:medium), :id => "tour-sample-image-" + hotel.photos.first.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
                    .back
                      .pad.tour-sample-image= image_tag hotel.photos.last.image(:medium), :id => "tour-sample-image-" + hotel.photos.last.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
                .clear-float 
                .some-info 
                  %p= hotel.city.country.title + ' , ' + hotel.city.title
              -if is_admin?
                .admin-btn-tour
                  = link_to 'مشاهده', hotel, :class => "btn btn-warning"   , :title => "آژانس_هواپیمایی_رادان_سیر"    
                  = link_to 'ویرایش', edit_hotel_path(hotel), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
                  = link_to 'حذف', hotel, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger", :title => "آژانس_هواپیمایی_رادان_سیر"
      

  

radan_travel/app/views/countries/show_fun_tours_for_country.html.haml
.margin3.margin-bottom{:style => "min-height:230px;"}
  - if @tour_group.present?
    .col-xs-12.margin-bottom
      .title-tour-line.col-xs-10
      %p.col-xs-3.set-center.title-tour{:class => I18n.locale}
        - if @country.category_country_id.present?
          = link_to @tour_group.title + ',' + @country.category_country.title+',' +@country.title  , @country.title  
        - else
          = link_to @tour_group.title + ','  +@country.title  , @country.title  
    = render '/tours/country_tour_groups', :category => @tour_group, :current_country => @country
    .show-tours.col-xs-10.set-center#Container
      - @country.tours.each do |country_tour|
        - if country_tour.continent_category_id == @tour_group.id 
          .tours-index{ "data-my-order" => country_tour.id, :style => "width:23%"}        
            - if country_tour.coming_soon?
              .coming_soon= image_tag 'coming.png'
            = link_to country_tour, :class => "tour-box" do 
              %h5.tour-title{:class => I18n.locale}= country_tour.title
              - if country_tour.photos.present?
                .tour-sample-image{:class => ('set-coming-soon' if country_tour.coming_soon?)}= image_tag country_tour.photos.first.image(:medium), :id => "tour-sample-image-" + country_tour.photos.first.id.to_s
              .clear-float
            .tour-date
              - if I18n.locale == :fa
                = render "/tours/show_persian_date", :tour => country_tour
              - else  
                = render "/tours/show_english_date", :tour => country_tour      
            -if is_admin?
              .admin-btn-tour
                = link_to 'ویرایش تور', edit_tour_path(country_tour), :class => "btn btn-info"
                = link_to 'مشاهده جزئیات', country_tour, :class => "btn btn-warning"                   
                = link_to 'حذف تور', country_tour, :method => :delete, :data => { :confirm => 'آیا می خواهید این تور را حذف کنید؟' }, :class => "btn btn-danger"
                = link_to 'ارسال به اعضا خبرنامه', sendtonewsletter_tour_path(country_tour), :class => "btn btn-default"       
                - @send_tour = @send_tour.to_i            
                - if @send_tour.present? && @send_tour == country_tour.id
                  .alert.alert-success='اطلاعات این تور برای اعضا خبرنامه ارسال شد.'