radan_travel/config/routes.rb
Rails.application.routes.draw do
  

  resources :iran_tour_reservs

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", :locale => /en|fa|ar/ do  
    resources :category_countries
    resources :continent_categories
    resources :visas
    resources :pdf_investments

    resources :investment_in_irans

    resources :passengers

    resources :visa_forms
    resources :visa_types

    resources :class_hotels
    resources :slides
    resources :locationtours do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end
    resources :custom_tours
    resources :planes
    resources :hotels do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end

    resources :cities do
      collection do
        get :dynamic_city
        get :show_fun_tours_for_city
      end
    end
    resources :countries do
      collection do
        get :show_fun_tours_for_country
      end
    end

    resources :tours do
      collection do
        post :search 
        get :tours_moment
        
      end
      member do
        get :sendtonewsletter
        get :iran_tour
      end
    end

    resources :photos

    resources :sights

    resources :links

    resources :roles

    devise_for :users
      
    resources :users

    resources :pages
    resources :send_links

    resources :customers do
      collection do
        post :search
        post :send_email_to_all
      end
    end

    resources :messages

    resources :tour_comments do
        member do
          get :confirm
        end
      end

  end
  
  root :to => 'static#index'
  get "index" => 'static#index'

  get "home" => 'static#home'

  get "google46bde3a8d7d48d7d" => 'static#google46bde3a8d7d48d7d'
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  get "BingSiteAuth.xml" => "static#BingSiteAuth", :format => "xml", :as => :BingSiteAuth
  
  get '/html_with_images', :to => 'tours#html_with_images'
  get '/html_with_table', :to => 'tours#html_with_table'
  get '/to_pdf_images', :to => 'tours#to_pdf_images'
  get '/to_pdf_table', :to => 'tours#to_pdf_table'
  get '/to_pdf_tour_show', :to => 'tours#to_pdf_tour_show'

  
end

radan_travel/app/models/city.rb
# encoding: UTF-8
class City < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :title_en
  belongs_to :country
  has_many :tours, dependent: :destroy
  has_many :hotels, dependent: :destroy
  has_many :sights, dependent: :destroy
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, reject_if: :all_blank, allow_destroy: true
  #has_and_belongs_to_many :locationtours
  def title
    if I18n.locale == :ar
      self.read_attribute("title_ar")
    elsif I18n.locale == :en
      self.read_attribute("title_en")
    else
      self.read_attribute("title_fa")
    end    
  end
  
  def text
    if I18n.locale == :ar
      self.read_attribute("text_ar")
    elsif I18n.locale == :en
      self.read_attribute("text_en")
    else
      self.read_attribute("text_fa")
    end    
  end
end

radan_travel/app/controllers/cities_controller.rb
# encoding: UTF-8
class CitiesController < ApplicationController
  before_action :set_city, only: [:show, :edit, :update, :destroy]

  # GET /cities
  # GET /cities.json
  def index
    @cities = City.all
  end

  # GET /cities/1
  # GET /cities/1.json
  def show
  end
  def show_fun_tours_for_city
    @city = City.find(params[:city_id])    
    @country = Country.find(params[:country_id])    
    @tour_group = ContinentCategory.find(params[:continent_id])
    
  end
  def dynamic_city
    p '...................'
    p country_id = params[:country_list]
    p @city = City.where( country_id: country_id)
    p '...................'
  end
  # GET /cities/new
  def new
    @city = City.new
  end

  # GET /cities/1/edit
  def edit
  end

  # POST /cities
  # POST /cities.json
  def create
    @city = City.new(city_params)

    respond_to do |format|
      if @city.save
        format.html { redirect_to @city, notice: 'City was successfully created.' }
        format.json { render :show, status: :created, location: @city }
      else
        format.html { render :new }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cities/1
  # PATCH/PUT /cities/1.json
  def update
    respond_to do |format|
      if @city.update(city_params)
        format.html { redirect_to @city, notice: 'City was successfully updated.' }
        format.json { render :show, status: :ok, location: @city }
      else
        format.html { render :edit }
        format.json { render json: @city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cities/1
  # DELETE /cities/1.json
  def destroy
    @city.destroy
    respond_to do |format|
      format.html { redirect_to cities_url, notice: 'City was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_city
      @city = City.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def city_params
      params.require(:city).permit(:title_fa, :title_en, :title_ar, :text_fa, :text_en, :text_ar, :country_id,
      photos_attributes: [:id, :image, :description_fa, :description_en, :description_ar, :city_id, :_destroy, :_update] 
      )
    end
end

radan_travel/app/helpers/cities_helper.rb
module CitiesHelper
end

radan_travel/app/views/cities/_form.html.haml
= nested_form_for @city, :html => { :multipart => true, :class => "form-horizontal"   } do |f|

  - if @city.errors.any?
    #error_explanation
      
      %ul
        - @city.errors.each do |attr, msg|
          %li= msg
  .row  
    .col-xs-12
      .col-xs-6
      .col-xs-6
        .form-group
          = f.label 'کشور مربوط را انتخاب کنید'   , :class => "control-label"       
          = f.select :country_id, options_for_select(Country.all.collect{ |u| [u.title_fa, u.id] }, :selected =>@city.country_id), prompt: "کشور را انتخاب کنید"
        .form-group
          = f.label 'عنوان فارسی', :class => "control-label"
          = f.text_field :title_fa, :class => "form-control"
        .form-group
          = f.label 'عنوان انگلیسی', :class => "control-label"
          = f.text_field :title_en, :class => "form-control"
        .form-group
          = f.label 'عنوان عربی', :class => "control-label"
          = f.text_field :title_ar, :class => "form-control"
          
    .col-xs-12            
      .form-group
        = f.label "برای افزودن تصاویر برای این پروژه دکمه زیر را فشار دهید و در کادری که نمایش داده می شود تصویر مورد نظر را انتخاب کنید:", :class => "control-label"
        = f.label "دقت داشته باشید حجم هر عکس باید کمتر از ۵۰۰کیلوبایت باشد.", :class => "control-label", :style=> "color:#ec523f"
        = f.link_to_add content_tag(:span, "افزودن تصویر", :class => "btn btn-warning"), :photos, :id => "add_new_picture", :class => "btn"
      .form-group  
        = f.fields_for :photos do |picture|  
          .col-xs-4
            = render "shared/upload_image_form", :picture => picture
    
    .col-xs-12
      .form-group
        = f.label 'متن فارسی', :class => "control-label"
        .editor
          = f.text_area :text_fa, :class => "ckeditor"
      .form-group
        = f.label 'متن انگلیسی', :class => "control-label"
        .editor
          = f.text_area :text_en, :class => "ckeditor"
      .form-group
        = f.label 'متن عربی', :class => "control-label"
        .editor
          = f.text_area :text_ar, :class => "ckeditor"
      .form-group
        = f.submit 'ثبت', :class => "btn btn-primary"

radan_travel/app/views/cities/dynamic_city.js.haml
$(document).ajaxStart(function(){  $('#loading').show();}).ajaxStop(function(){  $('#loading').hide();});
$('#sight_city_id, #tour_city_id').html("#{escape_javascript( options_from_collection_for_select(@city, :id, :title_fa))}");

radan_travel/app/views/cities/edit.html.haml
.margin3{:class => I18n.locale}
  %h1 ویرایش شهر
  = link_to 'مشاهده', @city, :class => "btn btn-warning"      
  = render 'form'

  
  

radan_travel/app/views/cities/index.html.haml
.margin3  
  %h1{:class => I18n.locale} لیست شهرها
  -if is_admin?
    = link_to 'تعریف شهر جدید', new_city_path, :class => "btn btn-success"
  %table.table.city
    %tr
      %th ردیف
      %th نام شهر
    
      %th کشور مربوط        
      %th تصویر    
      %th عملیات

    - @cities.each_with_index do |city, i|
      %tr
        %td= (i+1)
        %td= city.title 
             
        %td          
          - if city.country_id.present?
            = city.country.title
        %td   
          -if city.photos.present?
            = image_tag city.photos.first.image(:small)
        %td 
          -if is_admin?
            = link_to 'مشاهده', city, :class => "btn btn-warning"
            = link_to 'ویرایش', edit_city_path(city), :class => "btn btn-info"
            = link_to 'حذف', city, :method => :delete, :data => { :confirm => 'آیا مطمئن هستید؟' }, :class => "btn btn-danger"

radan_travel/app/views/cities/new.html.haml
.margin3
  %h1{:class => I18n.locale} شهر جدید
  = render 'form'

radan_travel/app/views/cities/show.html.haml
.margin3  
  - if is_admin?
    .col-xs-12
      = link_to 'ویرایش شهر', edit_country_path(@city), :class => "btn btn-info" 
  .col-xs-12.margin-bottom5
    .title-tour-line.col-xs-10
    %p.col-xs-3.set-center.title-tour{:class => I18n.locale}
      %span= link_to @city.country.title, @city.country
      
      %span= ' , ' + @city.title  
    
  .col-xs-12.margin-bottom5.country-text{:class => I18n.locale}
    =raw @city.text
      
  .col-xs-12.margin-bottom5  
    .col-xs-12.margin-bottom5
      .title-line.col-xs-10
      %p.col-xs-2.set-center.title{:class => I18n.locale}= t('hotel')
    .show-tours.col-xs-12.set-center{:class => I18n.locale}
      - @city.hotels.order('title_fa asc').each_with_index do |hotel, i|
        .tours-index{:class => "iran-city-" + hotel.city.id.to_s, "data-my-order" => hotel.id}
          = link_to hotel, :class => "tour-box", :title => "آژانس_هواپیمایی_رادان_سیر" do
            %h5.tour-title{:id => "hotel-"+hotel.id.to_s, :class => I18n.locale}= hotel.title          
            - if hotel.photos.present?
              .hover.panel{:id => "item-"+ (i+1).to_s}
                .front
                  .pad.tour-sample-image= image_tag hotel.photos.first.image(:medium), :id => "tour-sample-image-" + hotel.photos.first.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
                .back
                  .pad.tour-sample-image= image_tag hotel.photos.last.image(:medium), :id => "tour-sample-image-" + hotel.photos.last.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
            .clear-float 
            .some-info 
              %p
                %span=image_tag 'Star.png'
                - if hotel.class_hotel_id.present?
                  %span.en= hotel.class_hotel.title
              %p= hotel.city.country.title + ' , ' + hotel.city.title
          -if is_admin?
            .admin-btn-tour
              = link_to 'مشاهده', hotel, :class => "btn btn-warning"   , :title => "آژانس_هواپیمایی_رادان_سیر"    
              = link_to 'ویرایش', edit_hotel_path(hotel), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
              = link_to 'حذف', hotel, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => "btn btn-danger", :title => "آژانس_هواپیمایی_رادان_سیر"
        
  - if @city.sights.present?
    .col-xs-12.margin-bottom5
      .title-line.col-xs-10
      %p.col-xs-2.set-center.title{:class => I18n.locale}= t('places')
    .col-xs-12#show-city-places
      - @city.sights.each do |sight|        
        .tours-index
          = link_to sight, :class => "tour-box", :title => "آژانس_هواپیمایی_رادان_سیر" do
            %h5.tour-title{:id => 'sight-'+sight.id.to_s, :class => I18n.locale}= sight.title
            - if sight.photos.present?
              .tour-sample-image= image_tag sight.photos.first.image(:medium), :id => "tour-sample-image-" + sight.photos.first.id.to_s, :title => "آژانس_هواپیمایی_رادان_سیر", :alt => "آژانس_هواپیمایی_رادان_سیر"
            .clear-float

          -if is_admin?
            .admin-btn-tour
              = link_to 'ویرایش ', edit_sight_path(sight), :class => "btn btn-info", :title => "آژانس_هواپیمایی_رادان_سیر"
              = link_to 'مشاهده جزئیات', sight, :class => "btn btn-warning"       , :title => "آژانس_هواپیمایی_رادان_سیر"
              = link_to 'حذف ', sight, :method => :delete, :data => { :confirm => 'آیا می خواهید این تور را حذف کنید؟' }, :class => "btn btn-danger", :title => "آژانس_هواپیمایی_رادان_سیر"
  - if @city.photos.present?
    .col-xs-12     
      = render 'shared/items_images_sliders', :model => @city   

radan_travel/app/views/cities/show_fun_tours_for_city.html.haml
.margin3.margin-bottom{:style => "min-height:230px;"}
  - if @tour_group.present?
    .col-xs-12.margin-bottom
      .title-tour-line.col-xs-10
      %p.col-xs-3.set-center.title-tour{:class => I18n.locale}
        =link_to @tour_group.title + ',' +@country.title + ' , ' + @city.title, @city.title  
      
    
    = render '/tours/city_tour_groups', :category => @tour_group, :current_country => @country, :current_city => @city
    .show-tours.col-xs-10.set-center#Container
      - @country.tours.each do |country_tour|
        - if country_tour.continent_category_id == @tour_group.id && country_tour.city_id == @city.id
          .tours-index{ "data-my-order" => country_tour.id, :style => "width:23%"}        
            - if country_tour.coming_soon?
              .coming_soon= image_tag 'coming.png'
            = link_to country_tour, :class => "tour-box" do 
              %h5.tour-title{:class => I18n.locale}= country_tour.title
              - if country_tour.photos.present?
                .tour-sample-image{:class => ('set-coming-soon' if country_tour.coming_soon?)}= image_tag country_tour.photos.first.image(:medium), :id => "tour-sample-image-" + country_tour.photos.first.id.to_s
              .clear-float
            .tour-date
              - if I18n.locale == :fa
                = render "/tours/show_persian_date", :tour => country_tour
              - else  
                = render "/tours/show_english_date", :tour => country_tour      
            -if is_admin?
              .admin-btn-tour
                = link_to 'ویرایش تور', edit_tour_path(country_tour), :class => "btn btn-info"
                = link_to 'مشاهده جزئیات', country_tour, :class => "btn btn-warning"                   
                = link_to 'حذف تور', country_tour, :method => :delete, :data => { :confirm => 'آیا می خواهید این تور را حذف کنید؟' }, :class => "btn btn-danger"
                = link_to 'ارسال به اعضا خبرنامه', sendtonewsletter_tour_path(country_tour), :class => "btn btn-default"       
                - @send_tour = @send_tour.to_i            
                - if @send_tour.present? && @send_tour == country_tour.id
                  .alert.alert-success='اطلاعات این تور برای اعضا خبرنامه ارسال شد.'