radan_travel/config/routes.rb
Rails.application.routes.draw do
  

  resources :iran_tour_reservs

  mount Ckeditor::Engine => '/ckeditor'
  scope "(:locale)", :locale => /en|fa|ar/ do  
    resources :category_countries
    resources :continent_categories
    resources :visas
    resources :pdf_investments

    resources :investment_in_irans

    resources :passengers

    resources :visa_forms
    resources :visa_types

    resources :class_hotels
    resources :slides
    resources :locationtours do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end
    resources :custom_tours
    resources :planes
    resources :hotels do
      collection do
        get :dynamic_city
        get :dynamic_hotel
      end
    end

    resources :cities do
      collection do
        get :dynamic_city
        get :show_fun_tours_for_city
      end
    end
    resources :countries do
      collection do
        get :show_fun_tours_for_country
      end
    end

    resources :tours do
      collection do
        post :search 
        get :tours_moment
        
      end
      member do
        get :sendtonewsletter
        get :iran_tour
      end
    end

    resources :photos

    resources :sights

    resources :links

    resources :roles

    devise_for :users
      
    resources :users

    resources :pages
    resources :send_links

    resources :customers do
      collection do
        post :search
        post :send_email_to_all
      end
    end

    resources :messages

    resources :tour_comments do
        member do
          get :confirm
        end
      end

  end
  
  root :to => 'static#index'
  get "index" => 'static#index'

  get "home" => 'static#home'

  get "google46bde3a8d7d48d7d" => 'static#google46bde3a8d7d48d7d'
  get "sitemap.xml" => "static#sitemap", :format => "xml", :as => :sitemap
  get "BingSiteAuth.xml" => "static#BingSiteAuth", :format => "xml", :as => :BingSiteAuth
  
  get '/html_with_images', :to => 'tours#html_with_images'
  get '/html_with_table', :to => 'tours#html_with_table'
  get '/to_pdf_images', :to => 'tours#to_pdf_images'
  get '/to_pdf_table', :to => 'tours#to_pdf_table'
  get '/to_pdf_tour_show', :to => 'tours#to_pdf_tour_show'

  
end

radan_travel/app/models/customer.rb
# encoding: UTF-8
class Customer < ActiveRecord::Base
  extend FriendlyId  
  friendly_id :name
  has_attached_file :image, :styles => { :original => "200x150>" , :small => "100x50>" }
  
  validates_attachment :image, 
    :content_type => { :content_type => ["image/jpg", "image/jpeg", "image/png"], :message => "فرمت عکس صحیح می باشد." },
    :size => { :in => 0..300.kilobytes , :message => "حجم تصویر بیشتر از 300 کیلوبایت است."}
    
  validates :email, :format => { :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :message => 'ایمیل نامعتبر است.' } 
  
  def self.seach_in_club(customer_name)
    country_condition = "%" + customer_name + "%"  
    country_condition.blank? ? all : where("name LIKE ? ", country_condition)
  end
end

radan_travel/app/controllers/customers_controller.rb
# encoding: UTF-8
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.order(" created_at desc")
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end
  def send_email_to_all    
    subject = params[:subject]    
    text = params[:text]
    UserMailer.email_to_all_customer(subject, text).deliver
    flash[:ToAll] = 'پیام برای تمام اعضا خبرنامه ارسال شد'
    
    redirect_to :back
  end
  def search    
    customer_name = params[:name]
    if customer_name
      @customer_search_result = Customer.seach_in_club(customer_name)
    end
  end
  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      UserMailer.customer_register_done.deliver
      flash[:Ncustomer] = 'کاربر گرامی شما عضو خبرنامه شدید.'
    else
      flash[:Ecustomer] = 'کاربر گرامی ایمیل را صحیح وارد کنید.'
    end
    redirect_to :back
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :email, :phone, :address, :image)
    end
end

radan_travel/app/helpers/customers_helper.rb
module CustomersHelper
end

radan_travel/app/views/customers/_form.html.haml
= form_for @customer do |f|
  - if @customer.errors.any?
    .alert.alert-danger{:role => "alert"}
      %ul
        - @customer.errors.each do |attr, msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :email
    = f.text_field :email
  .field
    = f.label :phone
    = f.text_field :phone
  .field
    = f.label :address
    = f.text_field :address
  .actions
    = f.submit 'Save'

radan_travel/app/views/customers/edit.html.haml
%h1 Editing customer

= render 'form'

= link_to 'Show', @customer
\|
= link_to 'Back', customers_path

radan_travel/app/views/customers/index.html.haml
.margin3
  %h1{:class => I18n.locale}=  'لیست مشتریان'
  = link_to 'تعریف مشتری جدید', new_customer_path, :class => "btn btn-success"
  
  - if is_admin?      
    .col-xs-3
      - if flash[:ToAll].present?
        .alert.alert-success= flash[:ToAll]
    .col-xs-8
      .well
        = form_tag send_email_to_all_customers_path, :method => "post", id: "customer-tour" do 
          %h2{:class => I18n.locale}= 'ارسال پیام برای اعضای خبر نامه'
          .clear-float        
          
          .form-group
            = label_tag 'عنوان پیام'
          .form-group
            = text_field_tag :subject, params[:subject], :class => "form-control", :id => "customer-subject"
          .form-group
            = label_tag 'متن پیام'  
          .form-group
            = text_area_tag :text, params[:text], :class => "form-control", :id => "customer-text"
          .form-group
            = submit_tag 'ارسال پیام', :name => "tour_submit", :id => "customer-submit" , :class => "btn btn-info"
    
    .clear-float
  %table.table.table-striped{id:"customer_table"}
    %thead
      %tr
        %th ردیف‍
        %th نام 
        %th ایمیل
        %th تلفن 
        %th آدرس
        %th تاریخ عضویت در خبرنامه
        %th عملیات
    %tbody{:id => "customer_container"}
      - @customers.each_with_index do |customer, i|
        %tr
          %td= (i+1)
          %td= customer.name
          %td= customer.email
          %td= customer.phone
          %td= customer.address
          %td= JalaliDate.new(customer.created_at).strftime("%y/%m/%e %X")
          - if is_admin?
            %td
              = link_to 'ویرایش  اطلاعات مشتری', edit_customer_path(customer), :class => "btn btn-info"
              = link_to 'مشاهده جزئیات', customer, :class => "btn btn-warning"       
              = link_to 'حذف مشتری', customer, :method => :delete, :data => { :confirm => 'آیا می خواهید این مشتری را از حذف کنید؟' }, :class => "btn btn-danger"
        
:coffeescript
  window.reloadDataTable = ->
    if !!window.oTable
      window.oTable.fnDestroy(); 
    window.oTable = $("#customer_table").dataTable aoColumnDefs: [
      bSearchable: false
      aTargets: [0,6]
    ,  
      bSortable: false
      aTargets: [0,6]
    ],  oLanguage:
      sSearch: "جستجو:"
      sLengthMenu: "نمایش _MENU_ ردیف"
      sInfo: "جمع ردیفها _TOTAL_ ردیف (_START_ از _END_)"
      sZeroRecords: "هیچ داده ای وجود ندارد"
      sInfoEmpty: "هیچ موردی یافت نشد"
      sInfoFiltered: " - از بین _MAX_ داده موجود"
      oPaginate:
        sPrevious: "صفحه قبلی"
        sNext: "صفحه بعدی"

  window.reloadDataTable()

           

radan_travel/app/views/customers/new.html.haml
%h1 New customer

= render 'form'

= link_to 'Back', customers_path

radan_travel/app/views/customers/search.html.haml
.margin3
  
  - @customer_search_result.each do |customer|
    %p= customer.name
    %p= customer.email
    %p= customer.address

radan_travel/app/views/customers/show.html.haml
.margin3  
  %p#notice= notice

  %p
    %b Name:
    = @customer.name
  %p
    %b Email:
    = @customer.email
  %p
    %b Phone:
    = @customer.phone
  %p
    %b Address:
    = @customer.address

  = link_to 'Edit', edit_customer_path(@customer)
  \|
  = link_to 'Back', customers_path